// ============================================================
// Generate Static Data from Excel at Build Time
// Supports multiple functions: KAM, SALES, etc.
// Run: node generateStaticData.cjs
// Automatically runs before 'vite build' via package.json
// ============================================================
const path = require('path');
const fs = require('fs');
const { parseExcelData } = require('./parseExcel.cjs');

const PROJECT_DIR = __dirname;
const DATA_DIR = path.join(PROJECT_DIR, 'src', 'data');

// Same pattern as server.cjs
const FUNC_FILE_PATTERN = /^(\w+)_Dashboard_FY(\d+)\.xlsx$/i;

// Map function name → output file
const OUTPUT_MAP = {
  KAM: 'kamData.js',
  SALES: 'salesData.js',
};

// Map function name → header comment
const HEADER_MAP = {
  KAM: 'KAM (Key Account Management) OKR Dashboard Data',
  SALES: 'Sales OKR Dashboard Data',
};

/**
 * Scan the project directory for all {FUNCTION}_Dashboard_FY{NN}.xlsx files.
 * Returns an object: { KAM: '/path/to/KAM_Dashboard_FY26.xlsx', SALES: '/path/to/...' }
 * For each function, picks the highest FY number.
 */
function findAllExcelFiles() {
  const files = fs.readdirSync(PROJECT_DIR);
  const result = {};

  for (const filename of files) {
    const match = filename.match(FUNC_FILE_PATTERN);
    if (!match) continue;
    const func = match[1].toUpperCase();
    const fyNum = parseInt(match[2], 10);

    if (!result[func] || fyNum > result[func].fy) {
      result[func] = {
        fy: fyNum,
        filePath: path.join(PROJECT_DIR, filename),
        filename,
      };
    }
  }

  // Fallback for legacy KAM file
  if (!result.KAM) {
    const fallback = path.join(PROJECT_DIR, 'KAM_Dashboard_Input.xlsx');
    if (fs.existsSync(fallback)) {
      result.KAM = { fy: 0, filePath: fallback, filename: 'KAM_Dashboard_Input.xlsx' };
    }
  }

  return result;
}

/**
 * Generate an ES-module JS source file from parsed Excel data.
 */
function generateDataJS(data, funcName) {
  const timestamp = new Date().toISOString();
  const header = HEADER_MAP[funcName] || `${funcName} OKR Dashboard Data`;

  let src = '';
  src += '// ============================================================\n';
  src += `// ${header}\n`;
  src += `// AUTO-GENERATED by generateStaticData.cjs on ${timestamp}\n`;
  src += '// DO NOT EDIT MANUALLY -- update the Excel file and rebuild\n';
  src += '// ============================================================\n\n';

  src += '// Annual KPI Metrics\n';
  src += `export const annualMetrics = ${JSON.stringify(data.annualMetrics || {}, null, 2)};\n\n`;

  src += '// Monthly On-time Billing Data (INR Cr)\n';
  src += `export const monthlyBilling = ${JSON.stringify(data.monthlyBilling || [], null, 2)};\n\n`;

  src += '// Monthly On-time Collection Data (INR Cr)\n';
  src += `export const monthlyCollection = ${JSON.stringify(data.monthlyCollection || [], null, 2)};\n\n`;

  src += '// Quarterly QBRs Held\n';
  src += `export const quarterlyQBRs = ${JSON.stringify(data.quarterlyQBRs || [], null, 2)};\n\n`;

  src += '// Quarterly Hero Stories\n';
  src += `export const quarterlyHeroStories = ${JSON.stringify(data.quarterlyHeroStories || [], null, 2)};\n\n`;

  src += '// Quarterly New Logos\n';
  src += `export const quarterlyNewLogos = ${JSON.stringify(data.quarterlyNewLogos || [], null, 2)};\n\n`;

  src += '// New Logos Totals\n';
  src += `export const newLogosTotals = ${JSON.stringify(data.newLogosTotals || {}, null, 2)};\n\n`;

  src += '// Quarterly ARR (INR Cr)\n';
  src += `export const quarterlyARR = ${JSON.stringify(data.quarterlyARR || [], null, 2)};\n\n`;

  src += '// Quarterly Service Revenue (INR Cr)\n';
  src += `export const quarterlyServiceRev = ${JSON.stringify(data.quarterlyServiceRev || [], null, 2)};\n\n`;

  src += '// Account Owner Performance (YTD)\n';
  src += `export const accountOwnerPerformance = ${JSON.stringify(data.accountOwnerPerformance || [], null, 2)};\n\n`;

  src += '// Billing Totals\n';
  src += `export const billingTotals = ${JSON.stringify(data.billingTotals || {}, null, 2)};\n\n`;

  src += '// Collection Totals\n';
  src += `export const collectionTotals = ${JSON.stringify(data.collectionTotals || {}, null, 2)};\n\n`;

  src += '// Pipeline Coverage\n';
  src += `export const pipelineCoverage = ${JSON.stringify(data.pipelineCoverage || {}, null, 2)};\n\n`;

  // IMPORTANT: server outputs "weightages" but useKamData.js expects "defaultWeightages"
  src += '// Default OKR Weightages\n';
  src += `export const defaultWeightages = ${JSON.stringify(data.weightages || {}, null, 2)};\n\n`;

  src += '// Default RAG Metrics (user-entered Red/Amber/Green)\n';
  src += `export const defaultRagMetrics = ${JSON.stringify(data.ragMetrics || { capabilityAI: 'red', accountStrategy: 'red', archDomain: 'red' }, null, 2)};\n`;

  return src;
}

// --- Main ---
const allFiles = findAllExcelFiles();
const funcNames = Object.keys(allFiles);

if (funcNames.length === 0) {
  console.log('No Excel files found -- skipping static data generation');
  console.log('Static fallback data will remain unchanged.');
  process.exit(0);
}

// Ensure data directory exists
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

let generated = 0;
for (const func of funcNames) {
  const { filePath, filename } = allFiles[func];
  const outputFileName = OUTPUT_MAP[func] || `${func.toLowerCase()}Data.js`;
  const outputPath = path.join(DATA_DIR, outputFileName);

  console.log(`Parsing ${func}: ${filename}`);
  const data = parseExcelData(filePath);

  if (!data) {
    console.error(`  Failed to parse ${filename} -- ${outputFileName} unchanged`);
    continue;
  }

  const jsSource = generateDataJS(data, func);
  fs.writeFileSync(outputPath, jsSource, 'utf8');
  console.log(`  Updated: src/data/${outputFileName}`);
  generated++;
}

console.log(`\nGenerated ${generated} static data file(s).`);
