// ============================================================
// Generate Static Data (kamData.js) from Excel at Build Time
// Run: node generateStaticData.cjs
// Automatically runs before 'vite build' via package.json
// ============================================================
const path = require('path');
const fs = require('fs');
const { parseExcelData } = require('./parseExcel.cjs');

const PROJECT_DIR = __dirname;
const OUTPUT_FILE = path.join(PROJECT_DIR, 'src', 'data', 'kamData.js');

// Same pattern as server.cjs
const FUNC_FILE_PATTERN = /^(\w+)_Dashboard_FY(\d+)\.xlsx$/i;

function findDefaultExcelFile() {
  const files = fs.readdirSync(PROJECT_DIR);
  let bestFile = null;
  let bestFY = -1;

  for (const filename of files) {
    const match = filename.match(FUNC_FILE_PATTERN);
    if (match && match[1].toUpperCase() === 'KAM') {
      const fyNum = parseInt(match[2], 10);
      if (fyNum > bestFY) {
        bestFY = fyNum;
        bestFile = path.join(PROJECT_DIR, filename);
      }
    }
  }

  // Fallback
  if (!bestFile) {
    const fallback = path.join(PROJECT_DIR, 'KAM_Dashboard_Input.xlsx');
    if (fs.existsSync(fallback)) return fallback;
  }

  return bestFile;
}

function generateKamDataJS(data) {
  const timestamp = new Date().toISOString();

  let src = '';
  src += '// ============================================================\n';
  src += '// KAM (Key Account Management) OKR Dashboard Data\n';
  src += `// AUTO-GENERATED by generateStaticData.cjs on ${timestamp}\n`;
  src += '// DO NOT EDIT MANUALLY -- update the Excel file and rebuild\n';
  src += '// ============================================================\n\n';

  src += '// Annual KPI Metrics\n';
  src += `export const annualMetrics = ${JSON.stringify(data.annualMetrics || {}, null, 2)};\n\n`;

  src += '// Monthly On-time Billing Data (INR Cr)\n';
  src += `export const monthlyBilling = ${JSON.stringify(data.monthlyBilling || [], null, 2)};\n\n`;

  src += '// Monthly On-time Collection Data (INR Cr)\n';
  src += `export const monthlyCollection = ${JSON.stringify(data.monthlyCollection || [], null, 2)};\n\n`;

  src += '// Quarterly QBRs Held\n';
  src += `export const quarterlyQBRs = ${JSON.stringify(data.quarterlyQBRs || [], null, 2)};\n\n`;

  src += '// Quarterly Hero Stories\n';
  src += `export const quarterlyHeroStories = ${JSON.stringify(data.quarterlyHeroStories || [], null, 2)};\n\n`;

  src += '// Quarterly ARR (INR Cr)\n';
  src += `export const quarterlyARR = ${JSON.stringify(data.quarterlyARR || [], null, 2)};\n\n`;

  src += '// Quarterly Service Revenue (INR Cr)\n';
  src += `export const quarterlyServiceRev = ${JSON.stringify(data.quarterlyServiceRev || [], null, 2)};\n\n`;

  src += '// Account Owner Performance (YTD)\n';
  src += `export const accountOwnerPerformance = ${JSON.stringify(data.accountOwnerPerformance || [], null, 2)};\n\n`;

  src += '// Billing Totals\n';
  src += `export const billingTotals = ${JSON.stringify(data.billingTotals || {}, null, 2)};\n\n`;

  src += '// Collection Totals\n';
  src += `export const collectionTotals = ${JSON.stringify(data.collectionTotals || {}, null, 2)};\n\n`;

  src += '// Pipeline Coverage\n';
  src += `export const pipelineCoverage = ${JSON.stringify(data.pipelineCoverage || {}, null, 2)};\n\n`;

  // IMPORTANT: server outputs "weightages" but useKamData.js expects "defaultWeightages"
  src += '// Default OKR Weightages\n';
  src += `export const defaultWeightages = ${JSON.stringify(data.weightages || {}, null, 2)};\n`;

  return src;
}

// --- Main ---
const excelFile = findDefaultExcelFile();
if (!excelFile) {
  console.log('No KAM Excel file found -- skipping kamData.js generation');
  console.log('Static fallback data will remain unchanged.');
  process.exit(0);
}

console.log(`Generating static data from: ${path.basename(excelFile)}`);
const data = parseExcelData(excelFile);

if (!data) {
  console.error('Failed to parse Excel file -- kamData.js unchanged');
  process.exit(0); // don't fail the build
}

const jsSource = generateKamDataJS(data);
fs.writeFileSync(OUTPUT_FILE, jsSource, 'utf8');
console.log(`Updated: src/data/kamData.js`);
